# Description: Upload all the transformed data to the bucket
fa_submit prep  INPUT/TCGA-BRCA/META OUTPUT/R4/TCGA-BRCA/META/
fa_submit prep  INPUT/TCGA-ESCA/META OUTPUT/R4/TCGA-ESCA/META/
fa_submit prep  INPUT/TCGA-HNSC/META OUTPUT/R4/TCGA-HNSC/META/
fa_submit prep  INPUT/TCGA-KIRC/META OUTPUT/R4/TCGA-KIRC/META/
fa_submit prep  INPUT/TCGA-LUAD/META OUTPUT/R4/TCGA-LUAD/META/
fa_submit prep  INPUT/TCGA-LUSC/META OUTPUT/R4/TCGA-LUSC/META/

